spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://jz-ecommerce.cwrb7q3p0zpb.ap-northeast-2.rds.amazonaws.com:3306/jz
        username: jz
        password: jzecommerce
        initialization-mode: never  # always, embedded, never

    jpa:
        database: MYSQL
        properties:
            hibernate:
                default_batch_fetch_size: 500
                hbm2ddl:
                    auto: update      # create, create-drop, update, validate, none

    servlet:
        multipart:
            max-file-size: 20MB           # 파일 한 개당 최대 사이즈
            max-request-size: 100MB       # 요청당 최대 파일 크기

decorator:
    datasource:
        p6spy:
            # SQL 로그 찍기
            enable-logging: true

cloud:
    aws:
        s3:
            bucket: jshwang-ecommerce
            directory: items
        stack:
            auto: false
        region:
            static: ap-northeast-2
            auto: false
        credentials:
            instance-profile: true

front:
    url: http://juin.store
    cookie:
        domain: juin.store
