spring:
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update      # create, create-drop, update, validate, none

item-image:
    local-path-active: true
    original-path: ../Vue-Frontend/src/assets/items/original         # 상품 이미지 원본 업로드 경로
    thumbnail-path: ../Vue-Frontend/src/assets/items/thumbnail       # 상품 이미지 썸네일 업로드 경로