server:
    port: 12345

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jz?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
        username: root
        password: root
    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE
        serialization:
            fail-on-empty-beans: false
    mvc:
        hiddenmethod:
            filter:
                enabled: true

    jpa:
        database: MYSQL
        properties:
            hibernate:
                hbm2ddl:
                    auto: update      # create, create-drop, update, validate, none
#            show_sql: true   # 실행되는 쿼리 콘솔 출력
#            use_sql_comments: true # 추가적으로 주석 생성됨
#            format_sql: true # 쿼리 가독성 좋게 포맷팅


    servlet:
      multipart:
          max-file-size: 20MB           # 파일 한 개당 최대 사이즈
          max-request-size: 100MB       # 요청당 최대 파일 크

decorator:
    datasource:
        p6spy:
            # SQL 로그 찍기
            enable-logging: true

jwt:
    header: Authorization
    secret: SlotZUNvbW1lcmNlSlotZUNvbW1lcmNlSlotZUNvbW1lcmNlSlotZUNvbW1lcmNlSlotZUNvbW1lcmNlSlotZUNvbW1lcmNlSlotZUNvbW1lcmNlSlotZUNvbW1lcmNl
    token-validity-in-seconds: 86400

#itemImageLocation: C:/shop/item  # 상품 이미지 업로드 경로
#uploadPath: file:///C:/shop/           # 리소스 업로드 경로

item-image-location: ../frontend/src/assets/items/       # 상품 이미지 업로드 경로
uploadPath: file:///../frontend/src/assets/items/           # 리소스 업로드 경로

personalColorEndPoint: "http://localhost:55555/upload"